#!/usr/bin/env python3
"""Read the outreach reply inbox (IMAP) and update the CRM.

For each unseen message, match the sender address to a stored lead contact.
On match the message is classified first:

  - **Auto-reply** (RFC 3834 ``Auto-Submitted`` header, autoresponder
    headers, machine sender addresses, or stock phrases like "system
    generated auto reply" / "out of office"): logged as a 'note'
    interaction only. It does NOT set 'replied', does NOT cancel pending
    sends, and never triggers the unsubscribe heuristic — an acknowledgement
    bot is not a human decision.
  - **Genuine reply**: log a 'reply' interaction, set the lead
    outreach_status to 'replied', cancel pending scheduled outreach and
    campaign waves (auto-stop), and notify the operator at the platform
    inbox via ``mailer.operator_notify`` (sender, subject, fresh-text
    snippet) so a human sees it promptly.

Unsubscribe heuristic: if the subject or plain-text body contains
"unsubscribe" or "إلغاء الاشتراك", also mark the lead unsubscribed and log
an 'unsubscribe' interaction. The heuristic is labelled for operator review.

Bounce guard: delivery-failure messages (mailer-daemon / DSN subjects) are
matched back to the failed recipient. A matched bounce logs a 'bounce'
interaction, marks that contact's verification "invalid" (wave selection
skips invalid contacts), and cancels pending scheduled rows to that exact
address. Bounces are counted in a rolling 7-day window
(``data/bounce_guard.json``, override with ``BOUNCE_GUARD_FILE``); when the
bounce rate exceeds 5% of sent mail (minimum 10 sent), the operator is
notified once per episode at the platform inbox with the recommendation to
enable Hunter.io address verification — the agreed trigger for adopting it.

Never sends anything; matched messages are marked Seen. Unmatched messages
are left untouched.

Usage:
    python scripts/check_replies.py

Cron (e.g. every 15 minutes):
    */15 * * * * cd <repo>/hydra-shield-platform && .venv/bin/python scripts/check_replies.py
"""

from __future__ import annotations

import email
import email.policy
import imaplib
import json
import os
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional, Tuple

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.dashboard import mailer  # noqa: E402
from src.dashboard.marketing_store import MarketingStore  # noqa: E402

_UNSUBSCRIBE_KEYWORDS = ("unsubscribe", "إلغاء الاشتراك")

# Lines that mark the start of quoted history in a reply. Everything at or
# below the first marker is the original message echoed back — our own
# footer contains the word "unsubscribe", so scanning quoted text would
# mark every replying lead as unsubscribed.
_QUOTE_STARTERS = (
    "-----original message-----",
    "from:",  # quoted header block of the original
    "________________________________",  # Outlook divider
)
_QUOTE_WROTE_RE = re.compile(r"^on .+wrote:.*$", re.IGNORECASE)

# --- Auto-reply detection ---------------------------------------------------
# A system acknowledgement ("This is a system generated auto reply") is not a
# human answer: it must not stop outreach or mark a lead as replied.

# RFC 3834 plus common proprietary autoresponder headers.
_AUTO_HEADER_NAMES = (
    "x-autoreply",
    "x-autorespond",
    "x-auto-response-suppress",
    "x-autogenerated",
)
_AUTO_PRECEDENCE = {"auto_reply", "bulk", "junk", "list"}

# Machine sender local-parts that never write a human reply.
_AUTO_SENDER_PREFIXES = (
    "no-reply@", "noreply@", "do-not-reply@", "donotreply@",
    "mailer-daemon@", "postmaster@",
)

# Stock phrases in the freshly written text (matched case-insensitively on
# subject + top-of-body only — quoted history is stripped first).
_AUTO_BODY_PHRASES = (
    "system generated auto",
    "system-generated",
    "auto-reply",
    "autoreply",
    "auto reply",
    "automatic reply",
    "automated reply",
    "automated response",
    "automatic response",
    "out of office",
    "away from the office",
    "on vacation",
    "do not reply",
    "this message was sent automatically",
    "رد تلقائي",
    "رسالة تلقائية",
)


def _is_auto_reply(msg: "email.message.EmailMessage", from_addr: str,
                   subject: str, body: str) -> bool:
    """True when the message is a machine-generated acknowledgement, not a
    human reply. Checks RFC 3834 / autoresponder headers first, then the
    sender address, then stock phrases in the sender's fresh text."""
    auto_submitted = (msg.get("Auto-Submitted") or "").strip().lower()
    if auto_submitted and auto_submitted != "no":
        return True
    for name in _AUTO_HEADER_NAMES:
        if msg.get(name):
            return True
    precedence = (msg.get("Precedence") or "").strip().lower()
    if precedence in _AUTO_PRECEDENCE:
        return True
    if from_addr.lower().startswith(_AUTO_SENDER_PREFIXES):
        return True
    fresh = f"{subject or ''}\n{_top_reply_text(body)}".lower()
    return any(phrase in fresh for phrase in _AUTO_BODY_PHRASES)


# --- Bounce guard -------------------------------------------------------------
# Delivery-failure notices come from the receiving MTA (mailer-daemon /
# postmaster) or carry a DSN subject. The failed recipient appears in the
# body, never in From — so bounces are intercepted BEFORE the sender lookup.

_BOUNCE_SENDER_PREFIXES = ("mailer-daemon@", "postmaster@")
_BOUNCE_SUBJECT_MARKERS = (
    "delivery status notification",
    "undelivered mail",
    "delivery failure",
    "failure notice",
    "mail delivery failed",
    "returned mail",
    "undeliverable",
    "delivery has failed",
)
_EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")

# Alert policy (agreed Hunter.io trigger): warn once per episode when the
# 7-day bounce rate exceeds 5% of sent mail, with at least 10 sends in the
# window so a single early bounce cannot trip the alarm.
_BOUNCE_RATE_ALERT = 0.05
_BOUNCE_MIN_SAMPLE = 10
_BOUNCE_WINDOW_DAYS = 7


def _is_bounce(from_addr: str, subject: str) -> bool:
    """True for delivery-failure notices (MTA sender or DSN subject)."""
    low = (from_addr or "").lower()
    if low.startswith(_BOUNCE_SENDER_PREFIXES):
        return True
    subj = (subject or "").lower()
    return any(marker in subj for marker in _BOUNCE_SUBJECT_MARKERS)


def _find_bounced_contact(body: str, contacts: Dict[str, str]) -> Tuple[Optional[str], Optional[str]]:
    """Return (lead_slug, dead_address) for the first address in the bounce
    body that matches a stored contact — the recipient our send went to."""
    for addr in _EMAIL_RE.findall(body or ""):
        slug = contacts.get(addr.lower())
        if slug:
            return slug, addr.lower()
    return None, None


def _guard_path() -> str:
    return os.environ.get("BOUNCE_GUARD_FILE", str(ROOT / "data" / "bounce_guard.json"))


def _load_guard() -> Dict:
    try:
        with open(_guard_path(), "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {"days": {}, "hunter_notified": False}


def _save_guard(state: Dict) -> None:
    try:
        os.makedirs(os.path.dirname(_guard_path()), exist_ok=True)
        with open(_guard_path(), "w", encoding="utf-8") as fh:
            json.dump(state, fh, indent=1)
    except OSError as exc:
        print(f"bounce guard state not saved: {exc}")


def _guard_rate(state: Dict) -> Tuple[int, int, float]:
    """(sent, bounced, rate) over the rolling window."""
    cutoff = (datetime.utcnow() - timedelta(days=_BOUNCE_WINDOW_DAYS)).strftime("%Y-%m-%d")
    sent = bounced = 0
    for day, rec in (state.get("days") or {}).items():
        if day >= cutoff:
            sent += int(rec.get("sent", 0))
            bounced += int(rec.get("bounces", 0))
    rate = bounced / sent if sent else 0.0
    return sent, bounced, rate


def update_bounce_guard(store: MarketingStore, bounced: int = 0) -> Dict:
    """Sample today's sent count, add bounces, prune old days. Public for tests."""
    state = _load_guard()
    today = datetime.utcnow().strftime("%Y-%m-%d")
    day = state.setdefault("days", {}).setdefault(today, {"sent": 0, "bounces": 0})
    day["sent"] = store.sent_today_count()
    day["bounces"] = int(day.get("bounces", 0)) + bounced
    cutoff = (datetime.utcnow() - timedelta(days=_BOUNCE_WINDOW_DAYS * 2)).strftime("%Y-%m-%d")
    state["days"] = {d: r for d, r in state["days"].items() if d >= cutoff}
    _save_guard(state)
    return state


def maybe_alert_hunter(state: Dict) -> bool:
    """Notify the operator once per episode when the bounce rate crosses the
    agreed threshold — that crossing is the trigger for adopting Hunter.io
    address verification. Returns True when a notification was sent."""
    sent, bounced, rate = _guard_rate(state)
    if rate <= _BOUNCE_RATE_ALERT or sent < _BOUNCE_MIN_SAMPLE:
        if state.get("hunter_notified") and rate <= _BOUNCE_RATE_ALERT:
            state["hunter_notified"] = False  # episode over — re-arm
            _save_guard(state)
        return False
    if state.get("hunter_notified"):
        return False
    try:
        mailer.operator_notify(
            f"Bounce rate {rate:.0%} — Hunter.io verification now recommended",
            "The 7-day bounce rate crossed the agreed 5% threshold.\n"
            f"Window: {_BOUNCE_WINDOW_DAYS} days — {bounced} bounce(s) out of "
            f"{sent} sent.\n\n"
            "Agreed action (marketing/strategy/send_plan_2026-09.md): enable "
            "Hunter.io address verification before further sends — set "
            "HUNTER_API_KEY in the server .env. Until then, bounced contacts "
            "are marked invalid automatically and are skipped by wave selection.",
            kind="bounce_guard",
        )
    except Exception as exc:  # alerting must never break reply tracking
        print(f"bounce guard alert failed: {exc}")
        return False
    state["hunter_notified"] = True
    _save_guard(state)
    return True


def _handle_bounce(store: MarketingStore, email_msg: "email.message.EmailMessage",
                   contacts: Dict[str, str]) -> Optional[Tuple[str, str, bool]]:
    """Process a delivery-failure notice. Returns (lead_slug, 'bounce', False)
    when the failed recipient is a stored contact, else None."""
    subject = email_msg.get("Subject", "")
    date = email_msg.get("Date", "")
    body = _body_text(email_msg)
    lead_slug, dead = _find_bounced_contact(body, contacts)
    if not lead_slug or not dead:
        return None

    store.add_interaction(
        lead_slug,
        summary=f"Bounce: mail to {dead} failed ({subject}) ({date}) — "
                "address marked invalid",
        type="bounce",
    )
    for contact in store.list_contacts(lead_slug):
        if (contact.get("email") or "").lower() == dead:
            store.set_contact_verification(contact["id"], "invalid")
    cancelled = 0
    for row in store.list_scheduled(due_before="9999-12-31"):
        if (row["lead_slug"] == lead_slug and row["status"] == "scheduled"
                and (row["to_email"] or "").lower() == dead):
            if store.cancel_scheduled(row["id"]):
                cancelled += 1
    if cancelled:
        store.add_interaction(
            lead_slug,
            summary=f"Cancelled {cancelled} pending send(s) to bounced address {dead}.",
            type="note",
        )
    state = update_bounce_guard(store, bounced=1)
    maybe_alert_hunter(state)
    return lead_slug, "bounce", False


def _top_reply_text(body: str) -> str:
    """Keep only the freshly written part of a reply: drop ">"-quoted lines
    and everything below the first quote separator. The unsubscribe heuristic
    must judge the sender's own words, never our echoed footer."""
    kept = []
    for line in (body or "").splitlines():
        stripped = line.strip()
        low = stripped.lower()
        if stripped.startswith(">"):
            continue
        if _QUOTE_WROTE_RE.match(stripped):
            break
        if any(low.startswith(marker) for marker in _QUOTE_STARTERS):
            break
        kept.append(line)
    return "\n".join(kept)


def _env() -> Dict[str, Optional[str]]:
    return {
        "host": os.environ.get("IMAP_HOST"),
        "port": os.environ.get("IMAP_PORT", "993"),
        "user": os.environ.get("IMAP_USER"),
        "password": os.environ.get("IMAP_PASS") or os.environ.get("IMAP_PASSWORD"),
        "folder": os.environ.get("IMAP_FOLDER", "INBOX"),
    }


def _extract_address(from_header: str) -> Optional[str]:
    """Return the raw email address from a From header."""
    if not from_header:
        return None
    match = re.search(r"<([^>]+)>", from_header)
    if match:
        return match.group(1).lower().strip()
    if "@" in from_header and " " not in from_header:
        return from_header.lower().strip()
    return None


def _body_text(msg: email.message.EmailMessage) -> str:
    """Extract a plain-text body snippet for heuristic checks."""
    parts: List[str] = []
    if msg.is_multipart():
        for part in msg.walk():
            ctype = part.get_content_type() or ""
            if ctype == "text/plain":
                try:
                    payload = part.get_payload(decode=True)
                    if payload:
                        parts.append(payload.decode("utf-8", errors="ignore"))
                except Exception:
                    pass
    else:
        try:
            payload = msg.get_payload(decode=True)
            if payload:
                parts.append(payload.decode("utf-8", errors="ignore"))
        except Exception:
            pass
    return "\n".join(parts)[:2000]


def _has_unsubscribe_keyword(subject: str, body: str) -> bool:
    # Subject in full + only the freshly written top of the body (quoted
    # history is stripped — it contains our own unsubscribe footer).
    combined = f"{subject or ''}\n{_top_reply_text(body)}".lower()
    return any(kw.lower() in combined for kw in _UNSUBSCRIBE_KEYWORDS)


def _load_contacts(store: MarketingStore) -> Dict[str, str]:
    """Map lower-cased email -> lead_slug for all stored contacts."""
    mapping: Dict[str, str] = {}
    for contact in store.list_contacts():
        email_addr = (contact.get("email") or "").lower().strip()
        if email_addr:
            mapping[email_addr] = contact.get("lead_slug")
    return mapping


def _process_message(
    store: MarketingStore,
    email_msg: email.message.EmailMessage,
    contacts: Dict[str, str],
) -> Optional[Tuple[str, str, bool]]:
    """Process one parsed message.

    Returns ``(lead_slug, kind, is_unsub)`` where ``kind`` is ``"reply"``
    (human), ``"auto_reply"`` (machine acknowledgement) or ``"bounce"``
    (delivery failure) — or ``None`` when the message matches no stored
    lead contact.
    """
    from_addr = _extract_address(email_msg.get("From", ""))
    if not from_addr:
        return None

    # Bounces come from the MTA, not from the lead — intercept before the
    # sender lookup and match on the failed recipient in the body instead.
    if _is_bounce(from_addr, email_msg.get("Subject", "")):
        return _handle_bounce(store, email_msg, contacts)

    lead_slug = contacts.get(from_addr)
    if not lead_slug:
        return None

    subject = email_msg.get("Subject", "")
    date = email_msg.get("Date", "")
    body = _body_text(email_msg)

    if _is_auto_reply(email_msg, from_addr, subject, body):
        # Log it for the record only: no status change, no cancellation,
        # no unsubscribe heuristic — the machine said nothing about consent.
        store.add_interaction(
            lead_slug,
            summary=f"Auto-reply from {from_addr}: {subject} ({date}) — "
                    "not a human reply; outreach continues",
            type="note",
        )
        return lead_slug, "auto_reply", False

    unsub = _has_unsubscribe_keyword(subject, body)

    summary = f"Reply from {from_addr}: {subject} ({date})"
    if unsub:
        summary += " — unsubscribe keyword detected (heuristic; review)"

    store.add_interaction(
        lead_slug,
        summary=summary,
        type="reply",
    )
    store.update_state(lead_slug, outreach_status="replied")
    cancelled_scheduled = store.cancel_scheduled_for_lead(lead_slug)
    cancelled_waves = store.cancel_waves_for_lead(lead_slug)
    store.add_interaction(
        lead_slug,
        summary=(
            f"Auto-stopped outreach on reply: {cancelled_scheduled} scheduled row(s) "
            f"and {cancelled_waves} campaign wave(s) cancelled."
        ),
        type="note",
    )

    if unsub:
        store.unsubscribe(lead_slug, reason="reply keyword heuristic")
        store.add_interaction(
            lead_slug,
            summary=f"Unsubscribed via reply heuristic: {from_addr}",
            type="unsubscribe",
        )

    # Surface every genuine reply to the operator inbox: this is the moment
    # a human on the other side wants attention. Facts + fresh text only.
    fresh_text = " ".join(_top_reply_text(body).split())[:500]
    notice = (
        f"Lead: {lead_slug}\n"
        f"From: {from_addr}\n"
        f"Subject: {subject}\n"
        f"Date: {date}\n"
        f"Unsubscribe keyword: {'yes (heuristic)' if unsub else 'no'}\n"
        f"Outreach auto-stopped: {cancelled_scheduled} scheduled, "
        f"{cancelled_waves} wave(s) cancelled\n"
        f"Reply text (fresh part, truncated):\n{fresh_text or '(empty)'}"
    )
    try:
        mailer.operator_notify(
            f"Reply from lead {lead_slug} ({from_addr})",
            notice,
            kind="lead_reply",
        )
    except Exception as exc:  # notification must never break reply tracking
        print(f"operator notification failed for {lead_slug}: {exc}")

    return lead_slug, "reply", unsub


def main() -> int:
    cfg = _env()
    if not cfg["host"] or not cfg["user"] or not cfg["password"]:
        print("reply check unavailable: IMAP_* not configured")
        return 0

    store = MarketingStore()
    contacts = _load_contacts(store)
    if not contacts:
        print("reply check skipped: no stored contacts to match against")
        return 0

    # Keep the guard's daily sent sample fresh and evaluate the alert even
    # on quiet runs — the rate can cross the threshold as sends accumulate.
    maybe_alert_hunter(update_bounce_guard(store, 0))

    scanned = matched = replies = auto_replies = bounces = unsubscribed = 0
    try:
        port = int(cfg["port"])
        mail = imaplib.IMAP4_SSL(str(cfg["host"]), port)
        mail.login(str(cfg["user"]), str(cfg["password"]))
        mail.select(cfg["folder"])

        status, data = mail.search(None, "UNSEEN")
        if status != "OK" or not data or not data[0]:
            print("0 unseen messages")
            mail.close()
            mail.logout()
            return 0

        msg_ids = data[0].split()
        for msg_id in msg_ids:
            scanned += 1
            # BODY.PEEK[] — never sets \Seen implicitly. A plain (RFC822)
            # fetch marks every scanned message as read on the server
            # (RFC 3501), which made inbox mail look "opened by itself".
            # Only a matched reply earns the explicit \Seen below.
            status, msg_data = mail.fetch(msg_id, "(BODY.PEEK[])")
            if status != "OK" or not msg_data:
                continue
            raw = msg_data[0][1] if isinstance(msg_data[0], tuple) else None
            if raw is None:
                continue
            # policy.default is required: the legacy compat32 parser returns
            # a plain Message, which the isinstance gate below rejects —
            # with it, no message was ever processed at all.
            parsed = email.message_from_bytes(raw, policy=email.policy.default)
            if not isinstance(parsed, email.message.EmailMessage):
                continue
            result = _process_message(store, parsed, contacts)
            if result:
                matched += 1
                if result[1] == "reply":
                    replies += 1
                elif result[1] == "bounce":
                    bounces += 1
                else:
                    auto_replies += 1
                if result[2]:
                    unsubscribed += 1
                mail.store(msg_id, "+FLAGS", "\\Seen")

        mail.close()
        mail.logout()
    except Exception as exc:
        print(f"reply check failed: {exc}")
        return 1

    print(
        f"Replies checked: {scanned} scanned, {matched} matched "
        f"({replies} human, {auto_replies} auto, {bounces} bounces), "
        f"{unsubscribed} unsubscribed"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
