"""Tests for the static Knowledge Arm brief pages and their sitemap block.

The pages are build artifacts of config/briefs_registry.json, generated by
scripts/build_brief_pages.py. These tests fail when committed pages drift
from the registry — re-run the script and commit the result.
"""

import json
import os
import re

from src.climate import briefs_pages
from src.climate.briefs import load_briefs

_REPO = os.path.join(os.path.dirname(__file__), "..")
WEBSITE_DIR = os.path.join(_REPO, "website")
BRIEFS_DIR = os.path.join(WEBSITE_DIR, "briefs")
SITEMAP_PATH = os.path.join(WEBSITE_DIR, "sitemap.xml")

FRESHNESS_HINT = (
    "static brief page is stale — run "
    "`python scripts/build_brief_pages.py` and commit the result"
)


def _published():
    return [b for b in load_briefs().get("briefs", []) if b.get("status") == "published"]


def test_every_published_brief_has_a_fresh_static_page():
    published = _published()
    assert published, "expected at least one published brief"
    for brief in published:
        path = os.path.join(BRIEFS_DIR, f"{brief['id']}.html")
        assert os.path.exists(path), f"missing {path} — {FRESHNESS_HINT}"
        with open(path, "r", encoding="utf-8") as fh:
            assert fh.read() == briefs_pages.render_brief_page(brief), FRESHNESS_HINT


def test_no_orphan_static_pages():
    expected = {b["id"] + ".html" for b in _published()}
    on_disk = {f for f in os.listdir(BRIEFS_DIR) if f.endswith(".html")}
    orphans = on_disk - expected
    assert not orphans, f"orphan brief pages {sorted(orphans)} — {FRESHNESS_HINT}"


def test_page_carries_seo_essentials():
    brief = _published()[0]
    page = briefs_pages.render_brief_page(brief)
    assert f"<title>{brief['title']} — Talaix Knowledge Arm</title>" in page
    assert '<meta name="description"' in page
    assert f'<link rel="canonical" href="{briefs_pages.page_url(brief["id"])}">' in page
    assert '<meta property="og:type" content="article">' in page
    assert '<base href="../">' in page

    match = re.search(r'<script type="application/ld\+json">\s*(.*?)\s*</script>', page, re.S)
    assert match, "JSON-LD block missing"
    ld = json.loads(match.group(1))
    assert ld["@type"] == "Article"
    assert ld["headline"] == brief["title"]
    assert ld["datePublished"] == brief["date"]
    assert ld["isAccessibleForFree"] is True


def test_page_content_is_escaped():
    brief = _published()[0]
    page = briefs_pages.render_brief_page(brief)
    body = page.split("</head>", 1)[1]
    for section in brief.get("sections", []):
        assert section["heading"] in body
    # No raw HTML from registry content may leak into the page.
    assert "<script>alert" not in body
    for source in brief.get("sources", []):
        assert source["url"] in body


def test_sitemap_lists_every_brief_page():
    with open(SITEMAP_PATH, "r", encoding="utf-8") as fh:
        xml = fh.read()
    assert briefs_pages.SITEMAP_BEGIN in xml and briefs_pages.SITEMAP_END in xml, (
        f"sitemap briefs block missing — {FRESHNESS_HINT}"
    )
    for brief in _published():
        assert briefs_pages.page_url(brief["id"]) in xml, FRESHNESS_HINT


def test_sitemap_update_is_idempotent():
    with open(SITEMAP_PATH, "r", encoding="utf-8") as fh:
        xml = fh.read()
    once = briefs_pages.update_sitemap(xml, _published())
    twice = briefs_pages.update_sitemap(once, _published())
    assert once == twice


def test_renderer_is_deterministic():
    brief = _published()[0]
    assert briefs_pages.render_brief_page(brief) == briefs_pages.render_brief_page(brief)
